openapi: 3.0.1
info:
  title: 'My API'
  version: 1.0.0
paths:
  '/me':
    get:
      operationId: me
      responses:
        '200':
          description: Token data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenData'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenData'
  '/login':
    get:
      operationId: login
      security: [] # no auth needed
      responses:
        '200':
          description: Logged in succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenData'
components:
  schemas:
    TokenData:
      type: object
      properties:
        name:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: john@example.com
        iat:
          type: integer
          example: 1516239022
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - jwtAuth: []
