name: CI
on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_dir:
          - .
          - examples/express
          - examples/express-apikey-auth
          - examples/express-jwt-auth
          - examples/express-ts-mock
          - examples/express-typescript
          - examples/fastify
          - examples/hapi-typescript
          - examples/koa
          - examples/serverless-framework
          - examples/aws-sam
          - examples/aws-cdk
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v2
        if: matrix.project_dir == 'examples/aws-sam' || matrix.project_dir == 'examples/aws-cdk'
      - run: npm ci && npm run build
      - run: npm ci
        working-directory: ${{ matrix.project_dir }}
      - run: npm link ../../
        if: matrix.project_dir != '.' && matrix.project_dir != 'examples/aws-sam'
        working-directory: ${{ matrix.project_dir }}
      - run: npm run lint
        if: matrix.project_dir == '.'
        working-directory: ${{ matrix.project_dir }}
      - run: npm test
        working-directory: ${{ matrix.project_dir }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
